### ISSUE TITLE
where is WC_1.txt?

### ISSUE THREAD

**Issue by achaosss** [lupeterm/OBRG-Py#1]

**Comment by achaosss** [comment]
Python 3.10.11
numpy                     1.24.4
open3d                    0.18.0
no 3d picture output.Is the version question?

**Comment by achaosss** [comment]
I found the data. It comes from Stanford3dDataset_v1.2_Aligned_Version

**Comment by lupeterm** [comment]
Must've deleted it by accident. Let me put it back up @achaosss
